name: verify

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  _JAVA_OPTS: "-Xmx2g"
  GRADLE_OPTS: "-Dorg.gradle.workers.max=2 -Dorg.gradle.console=plain"

jobs:
  verify:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: openjdk
          java-version: 21
          cache: gradle

      - name: Install just and hurl
        run: |
          sudo apt-add-repository -y ppa:lepapareil/hurl
          sudo apt-get install -y just hurl

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - run: just ci verify

  release:
    needs: verify
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        with:
          release-type: simple

  # Publish the artifacts (only if `verify` passed, and `release` created release)
  publish:
    needs: [ verify, release ]
    if: needs.verify.result == 'success' && needs.release.outputs.released
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          just push
        shell: bash